// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1681575776);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1681575536);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1681575656);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1681575422);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.enabled", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 5);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.security_level.noscript_inited", true);
user_pref("browser.security_level.security_custom", false);
user_pref("browser.security_level.security_slider", 4);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230702050101");
user_pref("browser.startup.homepage_override.mstone", "102.9.0");
user_pref("browser.startup.homepage_override.torbrowser.version", "12.0.4");
user_pref("browser.theme.content-theme", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"torbutton-button\",\"security-level-button\",\"new-identity-button\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"PanelUI-contents\":[\"home-button\",\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"save-page-button\",\"print-button\",\"bookmarks-menu-button\",\"history-panelmenu\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"]},\"seen\":[\"developer-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":17,\"newElementCount\":1}");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "102.9.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.security.https_only_mode_ever_enabled_pbm", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20230702050101");
user_pref("extensions.lastAppVersion", "102.9.0");
user_pref("extensions.lastPlatformVersion", "102.9.0");
user_pref("extensions.lastTorBrowserVersion", "12.0.4");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.torbutton.cookiejar_migrated", true);
user_pref("extensions.torbutton.pref_fixup_version", 1);
user_pref("extensions.torbutton.startup", true);
user_pref("extensions.torlauncher.prompt_at_startup", false);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"0ac6a311-d5a6-4d56-8cac-e9983d3cd6aa\",\"onboarding@mozilla.org\":\"06d59ecc-dbfb-4cef-afbc-d0cb197778bd\",\"default-theme@mozilla.org\":\"f054eb33-7514-4ac0-9bbd-416f6e7c3aea\",\"ddg@search.mozilla.org\":\"097c48af-ab34-4785-b421-c8b2ed091afa\",\"youtube@search.mozilla.org\":\"14d42824-273c-4d2f-a847-cfe6e510feab\",\"google@search.mozilla.org\":\"e82a8dc3-6ba1-4624-97b2-859697fcd928\",\"blockchair@search.mozilla.org\":\"83e8d386-834b-463d-bbce-6fc32eb959ea\",\"ddg-onion@search.mozilla.org\":\"d1b781ef-19bb-43b4-ab42-d6494fcf239e\",\"blockchair-onion@search.mozilla.org\":\"fac7d835-5af1-4861-8600-a9e30d49663a\",\"startpage@search.mozilla.org\":\"3ffd8913-6c14-43f8-b3e0-021fe24ec938\",\"twitter@search.mozilla.org\":\"1a37761b-6ac7-45bd-aaaa-81dfaf82f32e\",\"wikipedia@search.mozilla.org\":\"d2cbd5db-09a3-48b5-8d2d-b5612b0aac35\",\"yahoo@search.mozilla.org\":\"f2ebe246-e7df-4d64-adf0-4fa957351f83\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20230702050101");
user_pref("gfx-shader-check.device-id", "0x1e84");
user_pref("gfx-shader-check.driver-version", "31.0.15.3161");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("gfx.blacklist.video-overlay", 4);
user_pref("gfx.blacklist.video-overlay.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("intl.accept_languages", "nl,en,en-us");
user_pref("intl.language_notification.shown", true);
user_pref("media.gmp-manager.buildID", "20230702050101");
user_pref("media.gmp-manager.lastCheck", 1681575603);
user_pref("media.gmp-manager.lastEmptyCheck", 1681575603);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.enabled", false);
user_pref("pref.browser.language.disable_button.down", false);
user_pref("privacy.history.custom", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.spoof_english", 1);
user_pref("sanity-test.device-id", "0x1e84");
user_pref("sanity-test.driver-version", "31.0.15.3161");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20230702050101");
user_pref("security.sandbox.content.tempDirSuffix", "{122c40bc-4485-471a-8fe0-40d0e1da4729}");
user_pref("toolkit.startup.last_success", 1681575505);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("torbrowser.migration.version", 1);
user_pref("torbrowser.settings.bridges.builtin_type", "");
user_pref("torbrowser.settings.bridges.enabled", false);
user_pref("torbrowser.settings.bridges.source", -1);
user_pref("torbrowser.settings.enabled", true);
user_pref("torbrowser.settings.firewall.enabled", false);
user_pref("torbrowser.settings.proxy.enabled", false);
user_pref("torbrowser.settings.quickstart.enabled", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
